name: "aws__deploy__qa"
description: "aws__deploy__qa"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install python dependencies
      shell: bash
      run: |
        pip install -r requirements-test.txt
        pip install -e .

    - name: Git Update Current Branch
      uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

    - name: Deploy Service to qa lambda function
      shell: bash
      run: |         
        pytest -rs ./tests/deploy_aws/test_Deploy__Service__to__qa.py