name: CI Pipeline - DEV
on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  GIT__BRANCH      : 'dev'
  RELEASE_TYPE     : 'minor'
  PACKAGE_NAME     : 'mgraph_ai_service_github_digest'
  TARGET_DEPLOY    : 'dev'

jobs:

  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start Local Stack
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/docker__local-stack@dev           # start LocalStack in GitHub actions
        with:
          LOCAL_STACK_SERVICES: 's3,lambda,iam,logs'

      - name: "run-tests"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pytest__run-tests@dev             # run tests (which use Local Stack)
        with:
          test_target: "tests/unit"
        env:
          FAST_API__AUTH__API_KEY__NAME  : 'api-key__in_github_test'
          FAST_API__AUTH__API_KEY__VALUE : 'this-is-the-value-of-the-api-key'

  increment-tag:
    name: Increment Tag - DEV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-tests

  aws_deplo_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Service Lambda function
        uses: ./.github/actions/aws__deploy__lambda
        env:
          AWS_SECRET_ACCESS_KEY          : ${{ secrets.AWS_SECRET_ACCESS_KEY          }}
          AWS_DEFAULT_REGION             : ${{ secrets.AWS_DEFAULT_REGION             }}
          AWS_ACCOUNT_ID                 : ${{ secrets.AWS_ACCOUNT_ID                 }}
          AWS_ACCESS_KEY_ID              : ${{ secrets.AWS_ACCESS_KEY_ID              }}
          FAST_API__AUTH__API_KEY__NAME  : ${{ secrets.FAST_API__AUTH__API_KEY__NAME  }}
          FAST_API__AUTH__API_KEY__VALUE : ${{ secrets.FAST_API__AUTH__API_KEY__VALUE }}
          IP_DATA__API_KEY               : ${{ secrets.IP_DATA__API_KEY               }}
        with:
          target  : ${{ env.TARGET_DEPLOY }}

    needs:
      - increment-tag
